### ISSUE TITLE
Manage authorization roles

### ISSUE THREAD

**Issue by kjetilhau** [equinor/fusion-project-portal#130]
We need to set administration roles for certain users so that we can lock down management endpoints.

As a starting point, we should introduce one role:
- Administrator / Portal Administrator

Ideally this role should be set in Azure AD and provided as part of the bearer token. Other options might be explored as well.

This role is assigned specific users that should be able to manage the portal configuration including:
- Onboard and manage apps 
- Onboard and manage contexts
- Manage AppGroups
- Manage WorkSurfaces
- Manage WorkSurface Apps (global and context specific)

Read endpoints should not require this role and should be available to all authenticated users.

Note that there might be need for more granular roles down the line.

**Comment by kjetilhau** [comment]
After a talk with Fusion Core, we have to viable solutions.

Solution 1:

We can create roles in the AppReg of the application(s)
Then we can add people to these roles from the Enterprise Applications pane.

By doing this, roles will automatically be included in the bearer token and be ready for interpretation in the application

---

Solution 2: 

We need to  create a global AD Group. This probably requires AccessIT. 
After that, we can assign users to this group.

When this is done, the last step is for Fusion Core to link this group to Fusion. 
We then have to perform a minor change in application code to get these roles included in the bearer token. 

---

Note that this needs to be performed for each environment. 

My conclusion:

Both of these solutions has the same end result. This means that we can, as a first step, quickly adopt solution 1 and migrate to solution 2 without any hassle og changes to the application. Therefore I suggest we go for solution 1 first to get it up and running.

@Noggling What do you think?

**Comment by Noggling** [comment]
I agree ;)
