### ISSUE TITLE
New Menu design

### ISSUE THREAD

**Issue by Noggling** [equinor/fusion-project-portal#148]
Hmmmf. Tought i saved the description i wrote on Friday but nooooo!! 
Okey her we go again.

# Description 

New menu design can be found [here](https://www.figma.com/file/q5vuYuz3nYzGSA1Yq43dmf/Master?type=design&node-id=5%3A47663&t=KKO0bZwAyznY6nes-1) but there the design as of may 15. has some features not supported.  These will be addressed in the limitation section. 

- [x] Remember to sort / order application groups, each group should have a sort order.
- [x] Remember to sort apps inside application groups, each item has a sort order.
- [ ] Error page for general error - Something went wrong. Please contact support.
- [x] Info message if no pinned apps on the pinned apps category. 
- [ ] If No context is selected the menu should noe display any content and it should have a no context selected message.
- [ ] Access message if the user dont have access (Im not sure if there is access polises on the context API)
- [x] All apps should look almost identical to what we have to day
- [x] I think CSS grid or flex is okey for now, enhancement on this can be a masonry layout but that can be implemented later if needed.

## Favorites
This functionality is supported to day but we only store the app key maybe we should look in to storing context-Id as well, sins some apps are only available on certain contexts. example of things stored.. maybe look in to disabling application pinned of not supported in context? 

```JSON
{
  "---contextId---": ["appkey1", "appkey2"],
}
```

## Limitations

- An App group will not have sub group functionality for now.
- Project, Contact, Facility and Portfolio tags will not be implemented as project is  the only one selectable at the moment.
- Most used apps functionality will should be recently visited and will at the moment only be stored in local storage.
- For now the pinned app functionality will be stored in local storage and a favorites v2 feature will be added for backend support.

## UX questions @chriispychiicken 

- How should the search functionality work? Should we search in the current App group or trough all applications?
- Sub groups will not be available

**Comment by Noggling** [comment]
New design is then required

**Comment by chrispgbv** [comment]
kan ha den redan ila dagen

**Comment by chrispgbv** [comment]
https://www.figma.com/file/7CGnv2IO4xFqBBlsZdRoPD/Project-Portal-Menu?node-id=22%3A20728&t=BHxVtUE74aKxuora-1 jeg mener jo at det hadde vært nice og byttet til noe sånn som dette
