### ISSUE TITLE
Faild to load application modules from script

### ISSUE THREAD

**Issue by Noggling** [equinor/fusion-project-portal#151]
![Skjermbilde 2023-04-24 kl  14 58 39](https://user-images.githubusercontent.com/28740201/234003324-61a52205-7fa5-4a67-8e34-dd97ddcbe4b1.png)

**Comment by Noggling** [comment]
Denne klarer jeg ikke å reprodusere.. @Gustav-Eikaas

**Comment by ken-mellem** [comment]
"Works on my machine" -  appears to be tricky to reproduce. Which again, makes it even more challenging to fix... closing
