### ISSUE TITLE
Client bundle file caching: Append bundle version to make sure new old versions is cleared

### ISSUE THREAD

**Issue by kjetilhau** [equinor/fusion-project-portal#174]
Require both backend and frontend changes.

Backend could set specific cache rules, e.g. limit caching to a certain time. But this will not guarantee a fresh bundle at all times. 

**Proposed solution:** 
Append a generated value to the file name, e.g. portal-client-bundle-12345.js.
The backend can then refer to any portal-client-bundle-*.js file that resides in that folder dynamically.

**Comment by Noggling** [comment]
The file name produces by the forntend will be 

> index.1235aa.js

so loading file like index.*.js should be sufficient.

PS: This fix may also fix som really major styling issues

**Comment by AreWiv** [comment]
@kjetilhau @Noggling How do I test/verify?

**Comment by kjetilhau** [comment]
@AreWiv Once the PR is approved, I will merge it to test. I will then assign it to you. 

All you really have to do is to verify that the portal is loading as expected. This is mostly internal changes.

**Comment by AreWiv** [comment]
Site seems to respond as expected. Reopen to set to Done.
