### ISSUE TITLE
Application Logging

### ISSUE THREAD

**Issue by Noggling** [equinor/fusion-project-portal#194]
See https://github.com/orgs/equinor/projects/415/views/7?pane=issue&itemId=29016285

What matrix do we need to log?

### Current situation

Both API and Webserver backends logs exceptions to ApplicationInsights

- [x] Add Application Insights to Portal API
- [x] Add Application Insights to Webserver backend
- [x] Add Application Insights to frontend
- [x] #270
- [ ] Add Dynatrace to applications
- [ ] Click analytics

**Comment by ken-mellem** [comment]
Create new for the remaining Dynatrace tasks. @kjetilhau
