### ISSUE TITLE
Project home page layout

### ISSUE THREAD

**Issue by Noggling** [equinor/fusion-project-portal#196]
The full design on the project page is not done, but we Have a layout example that can be implemented.
The header section should be simple to implement sins the only thing needed is to scale the image and have a propper placement of the view in One Equinor button.

If no image is present from STID then a default image will be required.
url example https://stiddata.equinor.com/public/OSA.jpg

This page should have its own error boundery.

![image](https://github.com/equinor/fusion-project-portal/assets/28740201/95ae19ea-1146-4dfc-991d-a58530b97eac)

**Comment by ken-mellem** [comment]
@Noggling Did you not push latest change out on Friday?

**Comment by ken-mellem** [comment]
@chriispychiicken tells me she has made some minor adjustments, so we need a follow up here.
