### ISSUE TITLE
Favorite Apps

### ISSUE THREAD

**Issue by Noggling** [equinor/fusion-project-portal#197]
The design is not yet finished but there is an preliminary implementation of this featur already in the portal. 
@chriispychiicken  will provide design

Implementation details:
- Provide a loading spinner og indication when applications are loading.
- Provide a propper description on how to add favorites / pinned apps when no apps are added.
- Provide a propper error message if application API is down and application data is not provided.

Questions for UX: @chriispychiicken 
- Should the applications have the same order and grouping as in the menu? or should we remove the allocation grouping 
- Maybe we should have grouping if the favorited apps are more than a certain number?

**Comment by ken-mellem** [comment]
@Noggling can this be closed?

**Comment by Noggling** [comment]
No this has not been done yet @ken-mellem
