### ISSUE TITLE
Domain for Project Portal

### ISSUE THREAD

**Issue by kjetilhau** [equinor/fusion-project-portal#221]
Currently, we use Radix domains for all environments. For production, we must establish a proper domain, e.g. **projects.fusion.equinor.com**. 

https://www.radix.equinor.com/guides/external-alias/#update-configuration

Decision from Hans:

Mainly: **project.fusion.equinor.com**, but also reserve **projects.fusion.equinor.com**

Certificates must be ordered and ensured maintained/rotated.

Contact: Ole Petter Gjøse

**Comment by kjetilhau** [comment]
project.fusion.equinor.com & projects.fusion.equinor.com DNS records have been added. Certificates needs to be ordered

**Comment by kjetilhau** [comment]
SSL certificate and intermediate has now been ordered for project.fusion.equinor.com

**Comment by ken-mellem** [comment]
[Service Now Ticket closed](https://equinor.service-now.com/selfservice?id=ticket&table=sc_req_item&sys_id=d45ffc3b474ba1d091ee5562e36d4356)

**Comment by kjetilhau** [comment]
Certificates added to Radix. project.fusion.equinor.com is now live

**Comment by kjetilhau** [comment]
DNS for both domains have been reserved. As directed from Hans Våga Dahle (DM), we will only use **project.fusion.equinor.com** for now. Closing this.
