### ISSUE TITLE
Delete old deployment configuration files

### ISSUE THREAD

**Issue by kjetilhau** [equinor/fusion-project-portal#232]
Before we migrated to Radix as a hosting and CD/CI platform, we used Azure App Services. There are still files in the project that is related to this but no longer in use. See https://github.com/equinor/fusion-project-portal/tree/main/.github/workflows and https://github.com/equinor/fusion-project-portal/tree/main/.config.

We still need to verify before deleting them.

**Comment by Noggling** [comment]
@kjetilhau This might be done ill look in to it :)
