### ISSUE TITLE
Legacy App - Loader App 

### ISSUE THREAD

**Issue by Noggling** [equinor/fusion-project-portal#259]
## Environments

All testing of issues are done in **project-portal-test**

- [project-portal-test](https://portal.fusion.equinor.com)
- [project-portal-test](https://webserver-fusion-project-portal-test.radix.equinor.com/)
- [project-portal-feature](https://webserver-fusion-project-portal-feature.radix.equinor.com/)

**Comment by ken-mellem** [comment]
Duplicate #106
