### ISSUE TITLE
Add IsLegacy column to OnboardedApp

### ISSUE THREAD

**Issue by kjetilhau** [equinor/fusion-project-portal#260]

**Comment by AreWiv** [comment]
@kjetilhau How do I access Onboardig App?

**Comment by kjetilhau** [comment]
@AreWiv 

Currently, there's no GUI for managing Onboarded Apps.
You can use the endpoints in Swagger: /api/onboarded-apps. See https://backend-fusion-project-portal-test.radix.equinor.com/swagger/index.html

When calling the GET endpoints, you should be able to see the property IsLegacy.

**Comment by AreWiv** [comment]
Verified - IsLegacy property is included when calling GET endpoints in Swagger.
Re-opened to set to Done.

**Comment by ken-mellem** [comment]
Remember to close the Issue too ;)
