### ISSUE TITLE
When context is not enable display message to user 

### ISSUE THREAD

**Issue by Noggling** [equinor/fusion-project-portal#266]
# Description 
Context that are not activated should not be available. this will result in a dialog saying the context has to be avtivated.

**Comment by AreWiv** [comment]
Describe context selection and activation better.

**Comment by AreWiv** [comment]
If context is selected the refresh page should navigate user to context page, this is not working.

**Comment by Noggling** [comment]
@AreWiv da er denne kalr for test

**Comment by AreWiv** [comment]
Reopened for changing status to Done.
Issue tested and verified and moved to Prod.

**Comment by AreWiv** [comment]
Issue tested and verified and moved to Prod.
