### ISSUE TITLE
Add title to onboarded contexts

### ISSUE THREAD

**Issue by Noggling** [equinor/fusion-project-portal#289]
## Expected outcome

> Short description 

Add and update title to onboarded context. 

## Business Value / Developer Experience

> Should give motivation for prioritization.
> Outcome measurement of delivered value.

There will be multiple usages for this update. 
- In  Admin View listing all onboarded contexts.
- Possible to list all available contexts on a worksurface on the portal home page

## User Acceptance Tests (UAT)

> How to test

When looking at the list of onboarded context it is had to distinguish each context a title will helt much here. 
changes need to be done to both

```
/api/onboarded-contexts
``` 
and 

```
/api/onboarded-contexts/{contextExternalId}
``` 

The already onboarded contexts should be updated with title. This should come from fusion context service, and not be prune to any user input.

## Environments

All testing of issues are done in **project-portal-test**

- [project-portal-prod](https://portal.fusion.equinor.com)
- [project-portal-test](https://webserver-fusion-project-portal-test.radix.equinor.com/)
- [project-portal-feature](https://webserver-fusion-project-portal-feature.radix.equinor.com/)

For Backend use these
  
- [project-portal-api-prod]([https://backend-fusion-project-portal-prod.radix.equinor.com/swagger/index.html))
- [project-portal-api-test](https://backend-fusion-project-portal-test.radix.equinor.com/swagger/index.html)
- [project-portal-api-feature](https://backend-fusion-project-portal-feature.radix.equinor.com/swagger/index.html)

**Comment by Jossilainen** [comment]
@kjetilhau @Noggling Could we look at this one together?

**Comment by kjetilhau** [comment]
For sure 👍
