### ISSUE TITLE
Index file missing 

### ISSUE THREAD

**Issue by Noggling** [equinor/fusion-project-portal#296]
## Description

some times the index file is missing in the portal se image 

![MicrosoftTeams-image](https://github.com/equinor/fusion-project-portal/assets/28740201/adad8f1f-eed4-44bf-a491-a07f59de72d9)

This may be related to new releases and the pod with the previous index file is removed.
@kjetilhau we need to discuss this to find a solution.

## Environments

All testing of issues are done in **project-portal-test**

- [project-portal-test](https://portal.fusion.equinor.com)
- [project-portal-test](https://webserver-fusion-project-portal-test.radix.equinor.com/)
- [project-portal-feature](https://webserver-fusion-project-portal-feature.radix.equinor.com/)

**Comment by Noggling** [comment]
This one is hard to test sins its probably only happening when new code is relesed.

**Comment by AreWiv** [comment]
Whattodo..?

**Comment by kjetilhau** [comment]
@Noggling

**Comment by Noggling** [comment]
@kjetilhau @AreWiv I dont know. Should we close and reopen if we experience it again?
