### ISSUE TITLE
fix: Scrollbars in Notifications and Work assigned

### ISSUE THREAD

**Issue by Noggling** [equinor/fusion-project-portal#299]
## Description
The scrollbars in Notifications and work assigned do not work properly, kpis an d actions should be sticky and items in the list should be scrollable. 

## Environments

All testing of issues are done in **project-portal-test**

- [project-portal-test](https://portal.fusion.equinor.com)
- [project-portal-test](https://webserver-fusion-project-portal-test.radix.equinor.com/)
- [project-portal-feature](https://webserver-fusion-project-portal-feature.radix.equinor.com/)

**Comment by ken-mellem** [comment]
Is this active?
