### ISSUE TITLE
🐛 Meetings crash when context cahnge

### ISSUE THREAD

**Issue by Noggling** [equinor/fusion-project-portal#306]
## Description

When opening a single meeting and then change the context the meeting application crashes this occurs because 
on context change the url is updated. and the update function uses a regex replace on first GUID, sins meeting cant have context in url the meeting guid is replaced. 

To prevent this one should check if context exist in url
By design from Fusion Core if there is a guid after appKey one can presume this is a context Guid and it safe to update.
This should be included in context url handling. 

```

```

## Environments

All testing of issues are done in **project-portal-test**

- [project-portal-prod](https://portal.fusion.equinor.com)
- [project-portal-test](https://webserver-fusion-project-portal-test.radix.equinor.com/)
- [project-portal-feature](https://webserver-fusion-project-portal-feature.radix.equinor.com/)

**Comment by Noggling** [comment]
@AreWiv denne er bare å teste. :)

**Comment by AreWiv** [comment]
@Noggling Testing project-portal-test: When being in Meeting (context JC), having selected a meeting and changing context to OGP, I am thrown out of Meeting just displaying the menu in an odd way. When changing context back to JC, I am back in Meeting. But not in the previously selected meeting.

**Comment by Noggling** [comment]
@AreWiv the sound slike the application is working as intended but you have not been able to test the issue. meetings is not enabled in ogp context, but can be found Kristin Sør Phase 1 context
