### ISSUE TITLE
Portal Admin UX/UI

### ISSUE THREAD

**Issue by Noggling** [equinor/fusion-project-portal#371]
## Expected outcome

> Short description 

A = Add
R = Remove
U = Update
D = Delete

- Worksurface - Generate surface with context type (multiple).  and list available. (Project, Facility, Contract) (ARUD)
- Onboarding Context. add Context, context list (ARUD)
- Create app group (ARUD)
- Onboard App 
- Add app to context.

https://github.com/equinor/lighthouse/blob/main/docs/project-portal/administration.md
https://github.com/equinor/lighthouse/blob/main/docs/project-portal/how-to/onboarding.md

## Business Value / Developer Experience

> Should give motivation for prioritization.
> Outcome measurement of delivered value.

## User Acceptance Tests (UAT)

> How to test

## Environments

All testing of issues are done in **project-portal-test**

- [project-portal-prod](https://portal.fusion.equinor.com)
- [project-portal-test](https://webserver-fusion-project-portal-test.radix.equinor.com/)
- [project-portal-feature](https://webserver-fusion-project-portal-feature.radix.equinor.com/)

For Backend use these
  
- [project-portal-api-prod](https://backend-fusion-project-portal-prod.radix.equinor.com/swagger/index.html)
- [project-portal-api-test](https://backend-fusion-project-portal-test.radix.equinor.com/swagger/index.html)
- [project-portal-api-feature](https://backend-fusion-project-portal-feature.radix.equinor.com/swagger/index.html)

**Comment by chriispychiicken** [comment]
Okei first outrcast bare tegn oppå eller skriv litt tilbakemelding om deter noe som ikke er tenkt på :) 

![Image](https://github.com/equinor/fusion-project-portal/assets/131761693/4da6c799-577d-4e81-b86f-bf78fa26b703)

**Comment by chriispychiicken** [comment]
![Image](https://github.com/equinor/fusion-project-portal/assets/131761693/f4985113-5811-421f-99eb-713bf87df5d3)



![Image](https://github.com/equinor/fusion-project-portal/assets/131761693/a3bd26b0-1976-4f69-9da1-2a3ae94e770e)

**Comment by Noggling** [comment]
![image](https://github.com/equinor/fusion-project-portal/assets/28740201/d5ba7c6d-b888-4bef-8acd-12c9c11e3f76)
her har du min take :) men tror en blanding vil funke fint

**Comment by Noggling** [comment]
@chriispychiicken  legger du inn link til Figma skissene du har laget her så lukker vi denne :)
