### ISSUE TITLE
🐛  Fix favorites links

### ISSUE THREAD

**Issue by Noggling** [equinor/fusion-project-portal#372]
## Expected outcome

> Short description 

Add a trailing slash ("/") to the end of the link to ensure that the contextId is appended correctly.

## Business Value / Developer Experience

> Should give motivation for prioritization.
> Outcome measurement of delivered value.@

Adding a trailing slash to links to ensure proper contextId appending is a small but impactful step that can contribute to various aspects of business success, including user satisfaction, data accuracy, cost reduction, brand reputation, conversion rates, and compliance.

 Working Sorftware

## User Acceptance Tests (UAT)

> How to test

To prevent the application from crashing, please follow these steps:

1. Add a pinned app.
2. Click on the link.

## Environments

All testing of issues are done in **project-portal-test**

- [project-portal-prod](https://portal.fusion.equinor.com)
- [project-portal-test](https://webserver-fusion-project-portal-test.radix.equinor.com/)
- [project-portal-feature](https://webserver-fusion-project-portal-feature.radix.equinor.com/)

For Backend use these
  
- [project-portal-api-prod]([https://backend-fusion-project-portal-prod.radix.equinor.com/swagger/index.html))
- [project-portal-api-test](https://backend-fusion-project-portal-test.radix.equinor.com/swagger/index.html)
- [project-portal-api-feature](https://backend-fusion-project-portal-feature.radix.equinor.com/swagger/index.html)

**Comment by AreWiv** [comment]
Tested and verified - deployed to Prod in Radix

**Comment by ken-mellem** [comment]
@AreWiv then please set status to Done.
