### ISSUE TITLE
Differences in Project portal Mettings compared to Fusion Meetings

### ISSUE THREAD

**Issue by TrondSLie** [equinor/fusion-project-portal#376]
/scroll bar in aggrid (should be removed in Meetings app) 
Is more visble in project portal because of color differnce on scrollbar
Screenshot Fusion Meetings
![image](https://github.com/equinor/fusion-project-portal/assets/90914278/8ec6d84a-5442-428d-b732-d3737e22ffb5)

Screenshot Project Portal Meetings
![image](https://github.com/equinor/fusion-project-portal/assets/90914278/d34456a5-0d5b-48d2-9473-a990c8f14fc8)

/double scrollbar on some tabs
Screenshot Fusion Meetings
![image](https://github.com/equinor/fusion-project-portal/assets/90914278/87ca6604-f4b5-44d8-9a13-8b16e92eef25)

Screenshot Project Portal Meetings
![image](https://github.com/equinor/fusion-project-portal/assets/90914278/8d3121ea-4d92-4a42-b16c-9802686f6074)

## Expected outcome

> Short description 

## Business Value / Developer Experience

> Should give motivation for prioritization.
> Outcome measurement of delivered value.

## User Acceptance Tests (UAT)

> How to test

## Environments

All testing of issues are done in **project-portal-test**

- [project-portal-prod](https://portal.fusion.equinor.com)
- [project-portal-test](https://webserver-fusion-project-portal-test.radix.equinor.com/)
- [project-portal-feature](https://webserver-fusion-project-portal-feature.radix.equinor.com/)

For Backend use these
  
- [project-portal-api-prod]([https://backend-fusion-project-portal-prod.radix.equinor.com/swagger/index.html))
- [project-portal-api-test](https://backend-fusion-project-portal-test.radix.equinor.com/swagger/index.html)
- [project-portal-api-feature](https://backend-fusion-project-portal-feature.radix.equinor.com/swagger/index.html)

**Comment by Noggling** [comment]
removing : /Pictures in helppage
Screenshot Fusion Meetings
![image](https://github.com/equinor/fusion-project-portal/assets/90914278/192b2213-b8ae-4ad9-aa83-7dd229f0f88a)

Screenshot Project Portal Meetings
![image](https://github.com/equinor/fusion-project-portal/assets/90914278/7423df3c-89a1-4b4e-8a51-4044eeb5d4de)


 and adding it to #320

**Comment by Noggling** [comment]
@AreWiv kan du verifisere ?

**Comment by AreWiv** [comment]
Tested and verified.
