### ISSUE TITLE
Group By design in workspace

### ISSUE THREAD

**Issue by chriispychiicken** [equinor/fusion-project-portal#382]
Group by needs to be changed so that when users come from old workspace to pp workspace they find group by and view settings easily. 

Figma link: https://www.figma.com/file/q5vuYuz3nYzGSA1Yq43dmf/Master?type=design&node-id=866-83153&mode=design&t=TbTlXNAa2SffWK2h-4

before: 
![bilde](https://github.com/equinor/fusion-project-portal/assets/131761693/536e26b4-a39d-40e2-9731-bd45b61e15c6)

after: 
![bilde](https://github.com/equinor/fusion-project-portal/assets/131761693/ca250053-d48e-40af-b4c6-cd4d78061039)

**Comment by ken-mellem** [comment]
@chriispychiicken  please provide a screenshot in the Description part here - so we can see what this is without going into Figma.

**Comment by espenkalle** [comment]
wip: https://github.com/equinor/cc-components/issues/624
