### ISSUE TITLE
Facility to project portal designs

### ISSUE THREAD

**Issue by chriispychiicken** [equinor/fusion-project-portal#383]
Design how having other contexts in the project portal will work / search

Figma link: https://www.figma.com/file/q5vuYuz3nYzGSA1Yq43dmf/Master?type=design&node-id=3-778&mode=design

**Comment by atlewee** [comment]
We need to implement support for **Project**, **Facility** and **Contract** context's.
@chriispychiicken  Do we have a design we can implement? Is there anything I can do to progress this further?

Background:
Contract context needed for ADS reports currently on their way into projectPortal.
Facility context needed to sunset legacy Fusion apps down the line.
