### ISSUE TITLE
Move all ADS reports to Project Control category

### ISSUE THREAD

**Issue by Gustav-Eikaas** [equinor/fusion-project-portal#475]
## Expected outcome
Ads reports were onboarded under different categories but the Product owner wants them all under the same category

**Comment by Noggling** [comment]
Ples use this template when providing issues : 
## Expected outcome

> Short description 

## Business Value / Developer Experience

> Should give motivation for prioritization.
> Outcome measurement of delivered value.

## User Acceptance Tests (UAT)

> How to test

## Environments

All testing of issues are done in **project-portal-test**

- [project-portal-prod](https://portal.fusion.equinor.com)
- [project-portal-test](https://webserver-fusion-project-portal-test.radix.equinor.com/)
- [project-portal-feature](https://webserver-fusion-project-portal-feature.radix.equinor.com/)

For Backend use these
  
- [project-portal-api-prod](https://backend-fusion-project-portal-prod.radix.equinor.com/swagger/index.html)
- [project-portal-api-test](https://backend-fusion-project-portal-test.radix.equinor.com/swagger/index.html)
- [project-portal-api-feature](https://backend-fusion-project-portal-feature.radix.equinor.com/swagger/index.html)

**Comment by Noggling** [comment]
please provide list of applications and what category the applications should be in.

**Comment by Noggling** [comment]
@Jossilainen var dette bare i test?
