### ISSUE TITLE
Remove milestones from the overview tab on project page

### ISSUE THREAD

**Issue by Noggling** [equinor/fusion-project-portal#576]
Certainly, here's an improved version:

## Expected Outcome
Upon verification and approval of the "Construction and Commissioning" tab, the milestones will be removed from the overview. and only visible on the "CC" tab.

## Business Value / Developer Experience
- group proCoSys data on singel tab

## User Acceptance Tests (UAT)
1. Verify that upon verification and approval of the tab, the milestones are removed from the overview.
3 Ensure that millstones are displayet on the  "Construction and Commissioning" tab.

All testing of issues are done in **project-portal-test**

- [project-portal-prod](https://portal.fusion.equinor.com)
- [project-portal-test](https://webserver-fusion-project-portal-test.radix.equinor.com/)
- [project-portal-feature](https://webserver-fusion-project-portal-feature.radix.equinor.com/)

For Backend use these
  
- [project-portal-api-prod](https://backend-fusion-project-portal-prod.radix.equinor.com/swagger/index.html)
- [project-portal-api-test](https://backend-fusion-project-portal-test.radix.equinor.com/swagger/index.html)
- [project-portal-api-feature](https://backend-fusion-project-portal-feature.radix.equinor.com/swagger/index.html)

**Comment by Jossilainen** [comment]
This seems to be fixed
