### ISSUE TITLE
Project portal uses scrollbars if resolution is lower than 4K

### ISSUE THREAD

**Issue by erlendthune** [equinor/fusion-project-portal#599]
## Expected outcome

When displaying the project portal in Full HD instead of 4K, I expect a different scrolling experience. See enclosed picture for explanation.

PS. The link to the production portal is wrong in the GitHUB template. It should be
- [project-portal-prod](https://project.fusion.equinor.com)
and not
- [project-portal-prod](https://portal.fusion.equinor.com)

## Business Value / Developer Experience

We can't expect our users to have 4K screens. They should have a good experience with lower screen resolutions.

## User Acceptance Tests (UAT)

F12
Toggle device emulation and change resolution to 1920x1080.
Notice that only part of the display is scrolled when the content is larger than the display area.

## Environments

All testing of issues are done in **project-portal-test**

- [project-portal-prod](https://project.fusion.equinor.com)

<img width="1156" alt="projectportalscroll" src="https://github.com/equinor/fusion-project-portal/assets/1288786/2713e7e7-c742-42be-a345-9de772113372">

**Comment by Noggling** [comment]
@erlendthune Thanks for the issue, but i think this is fixed in the current version of the portal. Kan you verify ?

**Comment by Jossilainen** [comment]
@erlendthune Can u verify if this is ok, so if it is I can close the issue?
