### ISSUE TITLE
Many login sessions on loading, by design? Investigate

### ISSUE THREAD

**Issue by Jossilainen** [equinor/fusion-project-portal#625]
## Expected outcome

![image](https://github.com/equinor/fusion-project-portal/assets/76108993/c8cbf5c8-853c-42a1-9c1f-57fc700e3533)

## Environments

All testing of issues are done in **project-portal-test**

- [project-portal-prod](https://portal.fusion.equinor.com)
- [project-portal-test](https://webserver-fusion-project-portal-test.radix.equinor.com/)
- [project-portal-feature](https://webserver-fusion-project-portal-feature.radix.equinor.com/)

For Backend use these
  
- [project-portal-api-prod](https://backend-fusion-project-portal-prod.radix.equinor.com/swagger/index.html)
- [project-portal-api-test](https://backend-fusion-project-portal-test.radix.equinor.com/swagger/index.html)
- [project-portal-api-feature](https://backend-fusion-project-portal-feature.radix.equinor.com/swagger/index.html)

**Comment by Jossilainen** [comment]
Not been able to re-create.

**Comment by Noggling** [comment]
I am not able to reproduce it and i dont se how i can fix without fusion core sins im using there module for authentication on frontend.
