### ISSUE TITLE
Investigate if SQL Password is needed

### ISSUE THREAD

**Issue by Jossilainen** [equinor/fusion-project-portal#652]
## Expected outcome

Investigate if SQL Password is needed in connection strings. Can we use entra-id in stead? What must be set up in azure, and how to set up radix.

Following keyvaults are used for connection strings now:
kv-pep-api-noe-prod
kv-pep-api-noe-test
kv-pep-api-noe-feature
kv-pep-noe-shared

SQL servers:
sql-pep-api-noe-feature
sql-pep-api-noe-test
sql-pep-api-noe-prod

## Business Value / Developer Experience

Eliminate hassle with updating passwords every 6 months or annually.

## Environments

All testing of issues are done in **project-portal-test**

- [project-portal-prod](https://portal.fusion.equinor.com)
- [project-portal-test](https://webserver-fusion-project-portal-test.radix.equinor.com/)
- [project-portal-feature](https://webserver-fusion-project-portal-feature.radix.equinor.com/)

For Backend use these
  
- [project-portal-api-prod](https://backend-fusion-project-portal-prod.radix.equinor.com/swagger/index.html)
- [project-portal-api-test](https://backend-fusion-project-portal-test.radix.equinor.com/swagger/index.html)
- [project-portal-api-feature](https://backend-fusion-project-portal-feature.radix.equinor.com/swagger/index.html)

**Comment by Jossilainen** [comment]
Waiting for infra

**Comment by Jossilainen** [comment]
Just waiting for infra to get help with best practice on how to do this. 

@nemanja-drobac has been assigned and should assign someone to have a look at this.

**Comment by ken-mellem** [comment]
@Jossilainen please follow this up.

**Comment by nemanja-drobac** [comment]
@Jossilainen do you have time today to discuss this? I can just come over to you if you are available and in the office?

**Comment by nemanja-drobac** [comment]
It is possible to get rid of password here and use Azure AD only auth. Radix team will come soon with more details.

**Comment by Richard87** [comment]
Hi! 

Dropping by, we just did this in Radix Vulnerability Scanner API, and in Radix Cost Allocation API that both uses Azure SQL Server/Database.

It requires a managed identity that are allowed access to your SQL Server, and federated credentials linked to Radix:
https://github.com/equinor/radix-vulnerability-scanner-api/blob/master/radixconfig.platform.yaml#L26
https://radix.equinor.com/guides/workload-identity/

When a Managed Identity have been linked to a Federated Credential in Radix, you can just use a DSN like this to authenticate: `server=%s;database=%s;fedauth=ActiveDirectoryDefault`  (https://github.com/equinor/radix-vulnerability-scanner-api/blob/master/repository/gorm_repository.go#L22C22-L22C74)


If you have a workflow where you automatically assigns users (like configuring a server in GitHub actions), the server needs the Directory Reader role. If you manually sets up the user and access control, the server will use your own token when verifying the service principal against MS Graph. If not, will use the severs identity

Equinor will only provide Directory Reader role for system-assigned identities for security reasons.

https://learn.microsoft.com/nb-no/azure/azure-sql/database/authentication-azure-ad-user-assigned-managed-identity?view=azuresql

**Comment by ken-mellem** [comment]
@Jossilainen can we get this in ?

**Comment by Jossilainen** [comment]
@ken-mellem will look into it.

**Comment by Richard87** [comment]
Hi! Absolutley, I have limited time tomorrow, (11.00 to 14.00), but am available all of wednesday and thursday :) 

Yes, for the SQL Server to authenticate a Entra user, it must have a system assigned identity, which has been assigned a Directory Reader role (which the `AzureAD Application Consent` team will set up after you have your system managed identity)

**Comment by Jossilainen** [comment]
Great, we'll look into it and try to contact you Wednesday.

**Comment by Richard87** [comment]
Yup, my calendar is wide open today :)
