### ISSUE TITLE
Fix SNYK vulnerabilities

### ISSUE THREAD

**Issue by Jossilainen** [equinor/fusion-project-portal#653]
## Expected outcome

Evaluate SNYK vulnerabilities listed as PR's for this repository and implement the relevant updates.

## Business Value / Developer Experience

Keeping software up to date.

## Environments

All testing of issues are done in **project-portal-test**

- [project-portal-prod](https://portal.fusion.equinor.com)
- [project-portal-test](https://webserver-fusion-project-portal-test.radix.equinor.com/)
- [project-portal-feature](https://webserver-fusion-project-portal-feature.radix.equinor.com/)

For Backend use these
  
- [project-portal-api-prod](https://backend-fusion-project-portal-prod.radix.equinor.com/swagger/index.html)
- [project-portal-api-test](https://backend-fusion-project-portal-test.radix.equinor.com/swagger/index.html)
- [project-portal-api-feature](https://backend-fusion-project-portal-feature.radix.equinor.com/swagger/index.html)

**Comment by Jossilainen** [comment]
Not able to build Legacy App Loader locally

**Comment by ken-mellem** [comment]
@EdwardBrunton duplicate?

**Comment by ken-mellem** [comment]
I will close - reopen if needed.
