### ISSUE TITLE
Add Portal endpoint resolving contexts related to an app

### ISSUE THREAD

**Issue by Jossilainen** [equinor/fusion-project-portal#708]
## Expected outcome

api/portals/{portalid}/apps{appkey}

Should return a list of contexts with all context-info

## Business Value / Developer Experience
Easier to edit context to apps

## Environments

All testing of issues are done in **project-portal-test**

- [project-portal-prod](https://portal.fusion.equinor.com)
- [project-portal-test](https://webserver-fusion-project-portal-test.radix.equinor.com/)
- [project-portal-feature](https://webserver-fusion-project-portal-feature.radix.equinor.com/)

For Backend use these
  
- [project-portal-api-prod](https://backend-fusion-project-portal-prod.radix.equinor.com/swagger/index.html)
- [project-portal-api-test](https://backend-fusion-project-portal-test.radix.equinor.com/swagger/index.html)
- [project-portal-api-feature](https://backend-fusion-project-portal-feature.radix.equinor.com/swagger/index.html)

**Comment by kjetilhau** [comment]
@Noggling Is the purpose of this endpoint to only show a list of related contexts to a certain app? Or is it expected to also return all data for an app? With the current endpoint path, it makes sense to return all data for an app as well

**Comment by Jossilainen** [comment]
@Noggling @kjetilhau, we should discuss this one, the endpoint is expected to return all data for the app, but append contexts. But from what I understood from @Noggling yesterday, he wanted this to be GET api/portals/{portalid}/onboarded-apps{appkey} in stead? Or did I miss something?

**Comment by Jossilainen** [comment]
Replaced by https://github.com/equinor/fusion-project-portal/issues/724
