### ISSUE TITLE
Context selector placeholder text

### ISSUE THREAD

**Issue by jaysencpp** [equinor/fusion-project-portal#72]
# Description
The placeholder text in the context selector is too long / The input field is too short / The X crashes with the text

![image](https://user-images.githubusercontent.com/28650210/220655541-2941f86e-7513-4a09-ad46-aac893105011.png)

**Comment by jaysencpp** [comment]
I'm also not able to close the dropdown options when I click outside of the dropdown.

**Comment by jaysencpp** [comment]
Also the X is hidden, but still clickable?
![image](https://user-images.githubusercontent.com/28650210/220657351-2b699a23-26cf-4f74-b85c-ab8734962b39.png)

**Comment by Noggling** [comment]
I have reported the X bug to core
