### ISSUE TITLE
Re-active tests as part of check-in gate

### ISSUE THREAD

**Issue by ken-mellem** [equinor/fusion-project-portal#722]
Execution of Integrations tests as part of the checks on the PR is not implemented. 

## Outcome
- [x] Make the tests part of the check-in gate.

**Comment by Gustav-Eikaas** [comment]
## Status
The action now works but the tests are not working in a "clean" environment due to a dependency on user-secrets. This is an error in the test setup. Its probably best if the test-authors fix this
