### ISSUE TITLE
📋 Fusion Application management 2.0 migration

### ISSUE THREAD

**Issue by Noggling** [equinor/fusion-project-portal#748]
## Expected outcome

Fusion core's Application management 2.0 is well on the way wee need to migrate to the new service.

```
https://fusion-s-apps-ci.azurewebsites.net/swagger/index.html
https://fusion-s-apps-test.azurewebsites.net/swagger/index.html
https://fusion-s-apps-fprd.azurewebsites.net/swagger/index.html
```

Al models need to be aligned with the new API service.

Maybe this issue should be handled as a tracker for the whole migration.
Changes needs to me made on all our api's and frontend.
- [ ] Backend
- [ ] Web Client
- [ ] Web Server

## Environments

All testing of issues are done in **project-portal-test**

- [project-portal-prod](https://portal.fusion.equinor.com)
- [project-portal-test](https://webserver-fusion-project-portal-test.radix.equinor.com/)
- [project-portal-feature](https://webserver-fusion-project-portal-feature.radix.equinor.com/)

For Backend use these
  
- [project-portal-api-prod](https://backend-fusion-project-portal-prod.radix.equinor.com/swagger/index.html)
- [project-portal-api-test](https://backend-fusion-project-portal-test.radix.equinor.com/swagger/index.html)
- [project-portal-api-feature](https://backend-fusion-project-portal-feature.radix.equinor.com/swagger/index.html)

## Work to be done

- [x] #802
- [x] #803
- [x] #804
- [x] #805

**Comment by Noggling** [comment]
We have a dependency on the Fusion Core frontend and are awaiting the next major release.

Once this is released, we can proceed.
https://statoil-proview.visualstudio.com/ProView%20Portal/_git/Project-Portal/pullrequest/3787

**Comment by ken-mellem** [comment]
> We have a dependency on the Fusion Core frontend and are awaiting the next major release.
> 
> Once this is released, we can proceed. https://statoil-proview.visualstudio.com/ProView%20Portal/_git/Project-Portal/pullrequest/3787

Appears this is completed now.

**Comment by ken-mellem** [comment]
@kjetilhau any particular reason why this is re-open?

**Comment by kjetilhau** [comment]
No, will close again
